## Блок catch и фильтры исключений

### Определение блока catch

За обработку исключения отвечает блок **catch**, который может иметь следующие формы:

- 
catch
{
    // выполняемые инструкции
}


- 
catch (тип_исключения)
{
    // выполняемые инструкции
}


- 
catch (тип_исключения имя_переменной)
{
    // выполняемые инструкции
}


### Фильтры исключений

Фильтры исключений позволяют обрабатывать исключения в зависимости от определенных условий. Для их применения 
после выражения catch идет выражение **when**, после которого в скобках указывается 
условие:

```cs
catch when(условие)
{
    
}
```

В этом случае обработка исключения в блоке catch производится только в том случае, если условие в выражении when истинно. 
Например:

```cs
int x = 1;
int y = 0;

try
{
    int result = x / y;
}
catch(DivideByZeroException) when (y==0 && x == 0)
{
    Console.WriteLine("y не должен быть равен 0");
}
catch(DivideByZeroException ex)
{
    Console.WriteLine(ex.Message);
}
```

В данном случае будет выброшено исключение, так как y=0. Здесь два блока catch, и оба они обрабатывают исключения типа 
DivideByZeroException, то есть по сути все исключения, генерируемые при делении на ноль. Но поскольку для первого блока указано условие 
**y == 0 && x == 0**, то оно не будет обрабатывать исключение - условие, указанное после оператора **when** 
возвращает false. Поэтому CLR будет дальше искать соответствующие блоки catch далее и для обработки исключения 
выберет второй блок catch. В итоге если мы уберем второй блок catch, то исключение вобще не будет обрабатываться.

