## Создание классов исключений

Если нас не устраивают встроенные типы исключений, то мы можем создать свои типы. Базовым классом 
для всех исключений является класс Exception, соответственно для создания своих типов мы можем унаследовать данный класс.

Допустим, у нас в программе будет ограничение по возрасту:

```cs
class Program
{
	static void Main(string[] args)
	{
		try
		{
			Person p = new Person { Name = "Tom", Age = 17 };
		}
		catch (Exception ex)
		{
			Console.WriteLine($"Ошибка: {ex.Message}");
		}
		Console.Read();
	}
}
class Person
{
	private int age;
	public string Name { get; set; }
	public int Age
	{
		get { return age; }
		set
		{
			if (value < 18)
			{
				throw new Exception("Лицам до 18 регистрация запрещена");
			}
			else
			{
				age = value;
			}
		}
	}
}
```

В классе Person при установке возраста происходит проверка, и если возраст меньше 18, то выбрасывается исключение. Класс Exception принимает 
в конструкторе в качестве параметра строку, которое затем передается в его свойство Message.

Но иногда удобнее использовать свои классы исключений. Например, в какой-то ситуации мы хотим обработать определенным образом только те исключения, 
которые относятся к классу Person. Для этих целей мы можем сделать специальный класс PersonException:

```cs
class PersonException : Exception
{
    public PersonException(string message)
        : base(message)
    { }
}
```

По сути класс кроме пустого конструктора ничего не имеет, и то в конструкторе мы просто обращаемся к конструктору базового класса 
Exception, передавая в него строку message. Но теперь мы можем изменить класс Person, чтобы он выбрасывал исключение именно этого типа и 
соответственно в основной программе обрабатывать это исключение:

```cs
class Program
{
	static void Main(string[] args)
	{
		try
		{
			Person p = new Person { Name = "Tom", Age = 17 };
		}
		catch (PersonException ex)
		{
			Console.WriteLine("Ошибка: " + ex.Message);
		}
		Console.Read();
	}
}
class Person
{
	private int age;
	public int Age
	{
		get { return age; }
		set
		{
			if (value < 18)
				throw new PersonException("Лицам до 18 регистрация запрещена");
            else
				age = value;
		}
	}
}
```

Однако необязательно наследовать свой класс исключений именно от типа Exception, можно взять какой-нибудь другой 
производный тип. Например, в данном случае мы можем взять тип ArgumentException, который представляет исключение, 
генерируемое в результате передачи аргументу метода некорректного значения:

```cs
class PersonException : ArgumentException
{
	public PersonException(string message)
		: base(message)
	{ }
}
```

Каждый тип исключений может определять какие-то свои свойства. Например, в данном случае мы можем определить в классе свойство для хранения устанавливаемого значения:

```cs
class PersonException : ArgumentException
{
	public int Value { get;}
	public PersonException(string message, int val)
		: base(message)
	{
		Value = val;
	}
}
```

В конструкторе класса мы устанавливаем это свойство и при обработке исключения мы его можем получить:

```cs
class Person
{
	public string Name { get; set; }
	private int age;
	public int Age
	{
		get { return age; }
		set
		{
			if (value < 18)
				throw new PersonException("Лицам до 18 регистрация запрещена", value);
			else
				age = value;
		}
	}
}
class Program
{
	static void Main(string[] args)
	{
		try
		{
			Person p = new Person { Name = "Tom", Age = 13 };
		}
		catch (PersonException ex)
		{
			Console.WriteLine($"Ошибка: {ex.Message}");
			Console.WriteLine($"Некорректное значение: {ex.Value}");
		}
		Console.Read();
	}
}
```

